### PR TITLE
Overhaul Docker implementation

### PR DESCRIPTION
**Pull request by KenHV**
Earlier, the Docker container stored the entire application data in a
volume, which is not how Docker should work. `config.php.json` and
SQLite (if used) now go in the data volume. Uploads are stored in a
separate volume.

Updates are handled seamlessly using a script. There is no need to run
`upgrade.php` manually.

The container now runs under the user `www-data` to ensure security. PHP
config has been changed to production config.

Issues with build cache due to improper use of apt have been resolved.
The image is now smaller.

A Docker Compose file has been added with instructions. Instructions are
also included in the README file.

### CODE REVIEW

**Comment by KenHV** [comment]
Upgrading to newer releases is still a hassle for now. I'll try to make this seamless when I can and make another PR.

**Comment by KenHV** [comment]
If you'd like, I can add a GitHub workflow that will build Docker images automatically when a new version is released. It'll save a lot of time for users.

**Comment by xenocrat** [comment]
Thanks for this PR. I will try to find time to have a proper look at it soon!

**Comment by xenocrat** [comment]
I've merged this PR. Thank you for taking the time to put this together and contribute it! Let me think about the workflow and get back to you.

**Pull request merged**
